# -*- coding: utf-8 -*-
"""Modelo CRR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rQYHKvj0Cu6-FynebJLBVFDvlzEEwn02
"""

import pandas as pd
import numpy as np

def modelo_CRR_Call(S, u, r, vettore_finale):
  d = 1/u
  p = ((1+r)-d)/(u-d)
  q = 1-p
  V1_sale = p*(vettore_finale[0])/(1+r)+q*(vettore_finale[1])/(1+r)
  V1_scende = p*(vettore_finale[1])/(1+r)+q*(vettore_finale[2])/(1+r)
  V0 = p*V1_sale/(1+r)+q*V1_scende/(1+r)
  print('Resultado Valoraciòn PUT CRR')
  print(vettore_finale)
  print(round(V1_sale, 4), round(V1_scende,4))
  print(round(V0, 4))

modelo_CRR_Call(10, 1.5, .015, [3.1, 1, 0])

